name: Docker Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      run: docker build -t yourusername/appname:latest .
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push Docker image
      run: docker push yourusername/appname:latest
    - name: Deploy Docker Container
      run: |
        ssh user@your-server 'docker pull yourusername/appname:latest && docker run -d -p 8080:8080 yourusername/appname'
