name: Python Application Deployment

on:
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Deploy to Server
      run: |
        scp -r . user@your-server:/path/to/deploy
        ssh user@your-server 'cd /path/to/deploy && python3 -m venv venv && source venv/bin/activate && pip install -r requirements.txt && nohup python3 app.py &'
